## KNN Algorithm

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# setting path equall to downloded file 
path="iris.data"

In [3]:
# assining coloumn name
headernames = ['sepal-length','sapal-width','petal-length','petal-width','class']

In [4]:
#read the given dataset to pandas dataframe
dataset=pd.read_csv(path,names=headernames)
dataset.head()

sepal-length  sapal-width  petal-length  petal-width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
#data process will be done through following 
x =dataset.iloc[:, :-1].values
y =dataset.iloc[:, 4].values

In [6]:
#next we will divide the data in trained and test set in 6:4 ratio
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y ,test_size=0.4)

In [7]:
#data scalling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()         #standardize feature by removing the mean & scaling to unit varience
scaler.fit(x_train)               #compute the mean and std. for later use
x_train=scaler.transform(x_train) #standerdise a dataset along any axis
x_test=scaler.transform(x_test)


In [8]:
#train the module using Kneighborclassifier class
from sklearn.neighbors import KNeighborsClassifier

#setting k value
clsfir = KNeighborsClassifier(n_neighbors=8)  
clsfir.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=8, p=2,
                     weights='uniform')

In [9]:
#pedicting y value on x dateset
y_pred= clsfir.predict(x_test)

In [10]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

#evaluate quality of output
#the higher the value of dignal element of confusion matrix higer will be the accuracy of prediction 
#dignal element represent the no. of point of pediction lable matching with truth table
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)


Confusion Matrix:
[[17  0  0]
 [ 0 19  0]
 [ 0  3 21]]


In [11]:
#build the test report showing the main classification matrices
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)

#accuracy classification score
#match y_test and y_prediction to give accuracy
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        17
Iris-versicolor       0.86      1.00      0.93        19
 Iris-virginica       1.00      0.88      0.93        24

       accuracy                           0.95        60
      macro avg       0.95      0.96      0.95        60
   weighted avg       0.96      0.95      0.95        60

Accuracy: 0.95
